FROM ubuntu:22.04

RUN \
	   apt-get update \
	&& apt-get install -y \
		cmake \
		checksec \
		gcc \
        make \
        tree \
        bash-completion \
        clang-tools \
        cppcheck \
        git \
        strace \
        vim \
        valgrind \
        net-tools \
        netcat-openbsd \
        tmux \
        libcurl4-gnutls-dev \
        libcurl4 \
        psmisc \
        htop

