name: Make me things

on: [ push ]

jobs:
  build_docker:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted

    # Using dind, otherwise we get root access errors
    container:
      image: docker:20.10-dind

    steps:

      - name: Check out the rep
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: junkyard6930/projenv
          tags: |
            "projenv:github_actions"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_release:
    name: Build Release
    runs-on: self-hosted
    container:
      image: junkyard6930/projenv:github_actions
    needs: build_docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Code
        run: (make)

  build_debug:
    name: Build Debug
    runs-on: self-hosted
    container:
      image: junkyard6930/projenv:github_actions
    needs: build_docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Code
        run: (make submodule && make libs && make debug)

  code_check:
    name: Static Code Check
    runs-on: self-hosted
    container:
      image: junkyard6930/projenv:github_actions
    needs: build_docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Code check
        run: (make pipeline_check)

  code_test:
    name: Unit Testing
    runs-on: self-hosted
    container:
      image: junkyard6930/projenv:github_actions
    needs: build_docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Code check
        run: (make pipeline_test)


  code_test:
    name: Memleak test
    runs-on: self-hosted
    container:
      image: junkyard6930/projenv:github_actions
    needs: build_docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Code check
        run: (make pipeline_test_mem)